name: Add Sentence
description: Add a sample sentence in Ladino and in at least on other language.
title: "Fraza mueva"
labels: ["example"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Una fraza en ladino, por egzempio:
        Alhad es el primer dia de la semana en Israel.
  - type: textarea
    id: ladino
    attributes:
      label: Ladino
      description: Una fraza en ladino.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Otra lingua
      description: A ke lingua vas a tradusir?
      options:
        - inglez
        - ebreo
        - fransez
        - portugez
        - turko
        - kasteyano
      multiple: false
      default: 0
    validations:
      required: true
  - type: textarea
    id: translation
    attributes:
      label: Teksto en la otra lingua
      description: Por favor eskrive aki la traduksion de la fraza en la otra lingua.

